[2022-10-18 11:20:11,441] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-18T18:19:10.537511+00:00 [queued]>
[2022-10-18 11:20:11,460] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-18T18:19:10.537511+00:00 [queued]>
[2022-10-18 11:20:11,460] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 11:20:11,461] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-18 11:20:11,461] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-18 11:20:11,497] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dbt_run> on 2022-10-18 18:19:10.537511+00:00
[2022-10-18 11:20:11,505] {standard_task_runner.py:52} INFO - Started process 269577 to run task
[2022-10-18 11:20:11,522] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag_bash', 'dbt_run', 'manual__2022-10-18T18:19:10.537511+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/dbt_bashOperator.py', '--cfg-path', '/tmp/tmphcayya_2', '--error-file', '/tmp/tmp1sm_wotf']
[2022-10-18 11:20:11,524] {standard_task_runner.py:80} INFO - Job 132: Subtask dbt_run
[2022-10-18 11:20:11,629] {task_command.py:370} INFO - Running <TaskInstance: dbt_dag_bash.dbt_run manual__2022-10-18T18:19:10.537511+00:00 [running]> on host ubuntu
[2022-10-18 11:20:11,684] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dbt_dag_bash
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-10-18T18:19:10.537511+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-18T18:19:10.537511+00:00
[2022-10-18 11:20:11,686] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-18 11:20:11,686] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /home/ubuntu/airflow/dbt_project/ && dbt run -m Core']
[2022-10-18 11:20:11,697] {subprocess.py:85} INFO - Output:
[2022-10-18 11:20:14,964] {subprocess.py:92} INFO - 18:20:14  Running with dbt=1.1.0
[2022-10-18 11:20:15,077] {subprocess.py:92} INFO - 18:20:15  Found 6 models, 5 tests, 6 snapshots, 0 analyses, 400 macros, 0 operations, 7 seed files, 2 sources, 0 exposures, 0 metrics
[2022-10-18 11:20:15,079] {subprocess.py:92} INFO - 18:20:15
[2022-10-18 11:20:24,110] {subprocess.py:92} INFO - 18:20:24  Concurrency: 2 threads (target='dev')
[2022-10-18 11:20:24,110] {subprocess.py:92} INFO - 18:20:24
[2022-10-18 11:20:24,115] {subprocess.py:92} INFO - 18:20:24  1 of 2 START incremental model DBT_HAMS71.Core_City ............................ [RUN]
[2022-10-18 11:20:24,132] {subprocess.py:92} INFO - 18:20:24  2 of 2 START incremental model DBT_HAMS71.Core_Transactions .................... [RUN]
[2022-10-18 11:20:31,671] {subprocess.py:92} INFO - 18:20:31  1 of 2 OK created incremental model DBT_HAMS71.Core_City ....................... [[32mSUCCESS 1[0m in 7.55s]
[2022-10-18 11:20:32,545] {subprocess.py:92} INFO - 18:20:32  2 of 2 OK created incremental model DBT_HAMS71.Core_Transactions ............... [[32mSUCCESS 1[0m in 8.41s]
[2022-10-18 11:20:32,549] {subprocess.py:92} INFO - 18:20:32
[2022-10-18 11:20:32,550] {subprocess.py:92} INFO - 18:20:32  Finished running 2 incremental models in 17.47s.
[2022-10-18 11:20:32,569] {subprocess.py:92} INFO - 18:20:32
[2022-10-18 11:20:32,570] {subprocess.py:92} INFO - 18:20:32  [32mCompleted successfully[0m
[2022-10-18 11:20:32,570] {subprocess.py:92} INFO - 18:20:32
[2022-10-18 11:20:32,570] {subprocess.py:92} INFO - 18:20:32  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2022-10-18 11:20:34,510] {subprocess.py:96} INFO - Command exited with return code 0
[2022-10-18 11:20:34,530] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dbt_dag_bash, task_id=dbt_run, execution_date=20221018T181910, start_date=20221018T182011, end_date=20221018T182034
[2022-10-18 11:20:34,569] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-18 11:20:34,587] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
